name = "subv2raydts"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "f5f59a86d5264009909034aa6c9acaea" }
]
